git add ./bil_site/celery.py
git add ./bil_site/settings.py
git add ./bil_site/urls.py
git add ./bil_site/wsgi.py
git add ./celeryconfig.py
git add ./ingest/apps.py
git add ./ingest/field_list.py
git add ./ingest/filters.py
git add ./ingest/forms.py
git add ./ingest/models.py
git add ./ingest/tables.py
git add ./ingest/tasks.py
git add ./ingest/templates
git add ./ingest/templates/ingest/base.html
git add ./ingest/templates/ingest/bootstrap_ingest.html
git add ./ingest/templates/ingest/collection_create.html
git add ./ingest/templates/ingest/collection_data_path.html
git add ./ingest/templates/ingest/collection_delete.html
git add ./ingest/templates/ingest/collection_detail.html
git add ./ingest/templates/ingest/collection_list.html
git add ./ingest/templates/ingest/collection_update.html
git add ./ingest/templates/ingest/collection_validation_results.html
git add ./ingest/templates/ingest/image_metadata_create.html
git add ./ingest/templates/ingest/image_metadata_delete.html
git add ./ingest/templates/ingest/image_metadata_detail.html
git add ./ingest/templates/ingest/image_metadata_list.html
git add ./ingest/templates/ingest/image_metadata_update.html
git add ./ingest/templates/ingest/image_metadata_upload.html
git add ./ingest/templates/ingest/index.html
git add ./ingest/templates/ingest/messages.html
git add ./ingest/templates/ingest/narrow.html
git add ./ingest/templates/ingest/signup.html
git add ./ingest/templates/ingest/wide.html
git add ./ingest/templates/ingest/collection_submission_results.html
git add ./ingest/templates/ingest/submit_validate_collection_list.html
git add ./ingest/templates/ingest/collection_list_obsolete.html
git add ./ingest/tests.py
git add ./ingest/urls.py
git add ./ingest/views.py
git add ./templates/registration/login.html
git add ./templates/registration/password_reset_complete.html
git add ./templates/registration/password_reset_confirm.html
git add ./templates/registration/password_reset_done.html
git add ./templates/registration/password_reset_email.html
git add ./templates/registration/password_reset_form.html
