# Generated by Django 3.1.12 on 2021-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20210622_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_bil_admin',
            field=models.BooleanField(default=False),
        ),
    ]
