# Generated by Django 3.1.14 on 2022-04-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_auto_20220331_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastate',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.specimen'),
        ),
        migrations.AddField(
            model_name='image',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.specimen'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.dataset'),
        ),
        migrations.AddField(
            model_name='publication',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.dataset'),
        ),
    ]
