# Generated by Django 3.1.14 on 2022-04-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20220412_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.specimen'),
        ),
    ]
