# Generated by Django 3.1.14 on 2022-04-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_instrument_specimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='ingest_method',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.project'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='project_funder',
            field=models.CharField(default='NIH', max_length=256),
        ),
    ]
