# Generated by Django 3.2.13 on 2022-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_auto_20220426_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFunders',
        ),
    ]
