# Generated by Django 3.2.13 on 2022-06-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_delete_projectfunders'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='doi',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='nameidentifier',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='nameidentifierscheme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='generalmodality',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='methods',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='other',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='socialmedia',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='subjectscheme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='technicalinfo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='technique',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='funder',
            name='award_number',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='funder',
            name='award_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='funder',
            name='funding_reference_identifier',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='funder',
            name='funding_reference_identifier_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='channels',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='dimensionorder',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='files',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='flurophore',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='gbytes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='landmarkname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='landmarkx',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='landmarky',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='landmarkz',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquexdim1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquexdim2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquexdim3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliqueydim1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliqueydim2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliqueydim3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquezdim1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquezdim2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='obliquezdim3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='representation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='slices',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='stepsizet',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='stepsizez',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='xsize',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='ysize',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='z',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='zsize',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='detectionwavelength',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='detectormodel',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='detectortype',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='illuminationtypes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='illuminationwavelength',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='objectiveimmersion',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='objectivemagnification',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='objectivena',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='objectivename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='sampletemperature',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmcid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='relatedidentifier',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='relatedidentifiertype',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='relationtype',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='atlas',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='genotype',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='localid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='locations',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='organlocalid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='organname',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
