# Generated by Django 3.2.13 on 2022-07-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_alter_dataset_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_version', models.CharField(blank=True, max_length=64, null=True)),
                ('dataset_doi', models.CharField(blank=True, max_length=512, null=True)),
                ('dataset_status', models.CharField(blank=True, max_length=256, null=True)),
                ('dataset_id_dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.descriptivemetadata')),
                ('dataset_id_ds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.dataset')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.eventslog')),
            ],
        ),
    ]
