# Generated by Django 3.2.18 on 2023-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_swc'),
    ]

    operations = [
        migrations.AddField(
            model_name='swc',
            name='swc_uuid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
