# Generated by Django 3.2.18 on 2023-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_consortium_projectconsortium'),
        ('ingest', '0016_swc_swc_uuid'),
    ]

    operations = [
    ]
