# Generated by Django 3.2.18 on 2023-06-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0017_merge_20230608_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_project', to='ingest.project')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='ingest.project')),
            ],
        ),
    ]
