# Generated by Django 3.2.18 on 2023-08-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0020_dataset_number_of_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_size',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='DOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_id', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata_version', models.IntegerField(blank=True, null=True)),
                ('v1_ds_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.descriptivemetadata')),
                ('v2_ds_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_ds_id', to='ingest.dataset')),
            ],
        ),
    ]
