# Generated by Django 3.2.18 on 2023-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0021_auto_20230824_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='doi',
            name='doi',
            field=models.BooleanField(default=False),
        ),
    ]
