# Generated by Django 3.2.18 on 2023-08-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0022_doi_doi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DOI',
            new_name='BIL_ID',
        ),
    ]
