# Generated by Django 3.2.18 on 2023-12-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0025_dataseteventslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(choices=[('bil', 'BIL'), ('nemo', 'Nemo'), ('dandi', 'Dandi'), ('cubietissue', 'CubieTissue')], default='', max_length=64)),
                ('data_id_2', models.CharField(blank=True, max_length=256, null=True)),
                ('relationship', models.CharField(choices=[('sequence data', 'Sequence Data'), ('neuron tracing', 'Neuron Tracing'), ('derived_data', 'Derived Data'), ('raw', 'Raw'), ('aligned', 'Aligned')], default='', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('linkage_date', models.DateField(blank=True, null=True)),
                ('data_id_1_bil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.bil_id')),
            ],
        ),
    ]
