# Generated by Django 3.2.18 on 2024-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0026_datasetlinkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('pi', 'PI'), ('data manager', 'Data Manager')], default='', max_length=64)),
                ('orcid', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('username', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bil_id',
            options={'verbose_name': 'BIL ID', 'verbose_name_plural': 'BIL IDs'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Dataset', 'verbose_name_plural': 'Datasets'},
        ),
    ]
