# Generated by Django 3.2.18 on 2024-02-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0026_datasetlinkage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bil_id',
            options={'verbose_name': 'BIL ID', 'verbose_name_plural': 'BIL IDs'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Dataset', 'verbose_name_plural': 'Datasets'},
        ),
        migrations.CreateModel(
            name='BIL_Specimen_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_spc_id', models.CharField(blank=True, max_length=256, null=True)),
                ('specimen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.specimen')),
            ],
        ),
        migrations.CreateModel(
            name='BIL_Project_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_prj_id', models.CharField(blank=True, max_length=256, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.project')),
            ],
        ),
        migrations.CreateModel(
            name='BIL_Instrument_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_ins_id', models.CharField(blank=True, max_length=256, null=True)),
                ('instrument_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.instrument')),
            ],
        ),
    ]
