# Generated by Django 3.2.18 on 2024-03-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0027_auto_20240205_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id_2', models.CharField(blank=True, max_length=256, null=True)),
                ('code_id', models.CharField(choices=[('cubietissue', 'CubieTissue')], default='', max_length=64)),
                ('specimen_category', models.CharField(choices=[('tissue', 'Tissue'), ('roi', 'ROI'), ('slab', 'Slab'), ('donor', 'Donor')], default='', max_length=64)),
                ('specimen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.bil_specimen_id')),
            ],
        ),
    ]
