# Generated by Django 3.2.18 on 2024-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0028_specimenlinkage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenlinkage',
            name='code_id',
            field=models.CharField(choices=[('cubie_tissue', 'Cubie Tissue')], default='', max_length=64),
        ),
    ]
