# Generated by Django 3.2.18 on 2024-07-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0030_auto_20240624_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettag',
            name='bil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingest.bil_id'),
        ),
    ]
