# Generated by Django 3.2.18 on 2024-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0033_auto_20240716_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='methods',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='DatasetTag',
        ),
    ]
