# Generated by Django 3.2.18 on 2024-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0035_auto_20241016_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettag',
            name='tag',
            field=models.CharField(max_length=512),
        ),
    ]
