# Generated by Django 3.2.18 on 2024-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0037_alter_dataset_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='methods',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='datasettag',
            name='tag',
            field=models.CharField(max_length=256),
        ),
    ]
