# Generated by Django 3.2.18 on 2024-10-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0038_auto_20241021_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsortiumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ingest.consortium')),
            ],
        ),
        migrations.AlterField(
            model_name='datasettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.consortiumtag'),
        ),
    ]
