# Generated by Django 3.2.18 on 2025-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0041_alter_dataset_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenlinkage',
            name='specimen_category',
            field=models.CharField(choices=[('tissue', 'Tissue'), ('roi', 'ROI'), ('slab', 'Slab'), ('donor', 'Donor'), ('section', 'Section')], default='', max_length=64),
        ),
    ]
