# Generated by Django 3.2.18 on 2025-11-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0042_alter_specimenlinkage_specimen_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlinkage',
            name='code_id',
            field=models.CharField(choices=[('bil', 'BIL'), ('nemo', 'Nemo'), ('dandi', 'Dandi')], default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Spatial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataavailability', models.CharField(max_length=256)),
                ('histologicalstainname', models.CharField(blank=True, max_length=256)),
                ('nuclearstainname', models.CharField(blank=True, max_length=256)),
                ('probesetdoi', models.CharField(blank=True, max_length=256)),
                ('probesequencesdoi', models.CharField(blank=True, max_length=256)),
                ('lighttreatmenttime', models.CharField(blank=True, max_length=256)),
                ('lighttreatmenttimeunits', models.CharField(blank=True, max_length=256)),
                ('numbertargetedrna', models.CharField(blank=True, max_length=256)),
                ('genepanelname', models.CharField(blank=True, max_length=256)),
                ('platformname', models.CharField(blank=True, max_length=256)),
                ('machinename', models.CharField(blank=True, max_length=256)),
                ('machinesoftwareversion', models.CharField(blank=True, max_length=256)),
                ('numberzsections', models.CharField(blank=True, max_length=256)),
                ('segmentationmethod', models.CharField(blank=True, max_length=256)),
                ('segmentationmodel', models.CharField(blank=True, max_length=256)),
                ('segmentationmethodversion', models.CharField(blank=True, max_length=256)),
                ('clusteringmethod', models.CharField(blank=True, max_length=256)),
                ('labeltransfermethod', models.CharField(blank=True, max_length=256)),
                ('labeltransferreference', models.CharField(blank=True, max_length=256)),
                ('nuclearimagetransform', models.CharField(blank=True, max_length=256)),
                ('histologicalimagetransform', models.CharField(blank=True, max_length=256)),
                ('xyzposition', models.CharField(blank=True, max_length=256)),
                ('cellid', models.CharField(blank=True, max_length=256)),
                ('cellcentroidlocation', models.CharField(blank=True, max_length=256)),
                ('cellareavolume', models.CharField(blank=True, max_length=256)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.dataset')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingest.sheet')),
            ],
        ),
    ]
