# Generated by Django 3.2.18 on 2025-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0043_auto_20251118_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatial',
            name='filtercriteria',
            field=models.TextField(blank=True),
        ),
    ]
