# Generated by Django 3.2.18 on 2026-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0044_spatial_filtercriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='has_reviewed_brain_initiative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_brain_initiative',
            field=models.BooleanField(default=False),
        ),
    ]
