# Generated by Django 5.2.16 on 2026-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0045_auto_20260423_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventslog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("mail_tapes_to_bil", "Mail Tapes To BIL"),
                    ("tapes_received", "Tapes Received"),
                    ("tapes_ready_for_qc", "Tapes Ready For QC"),
                    ("move_to_collection", "Move To Collection"),
                    ("request_brainball", "Request Brainball"),
                    ("Mail_brainball_from_bil", "Mail Brainball From BIL"),
                    ("mail_brainball_to_bil", "Mail Brainball To BIL"),
                    ("received_brainball", "Received Brainball"),
                    ("collection_created", "Collection Created"),
                    ("metadata_uploaded", "Metadata Uploaded"),
                    ("request_validation", "Request Validation"),
                    ("request_submission", "Request Submission"),
                    ("request_embargo", "Request Embargo"),
                    ("collection_public", "Collection Public"),
                    ("request_withdrawal", "Request Withdrawal"),
                    ("data_curated", "Data Curated"),
                    ("collection_validated", "Collected Validated"),
                    ("user_action_required", "User Action Required"),
                    ("updated_to_v2", "Updated to V2"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
