attrs = [
    'organization_name',
    'project_name',
    'project_description',
    'project_funder_id',
    'background_strain',
    'image_filename_pattern',
    'lab_name',
    'submitter_email',
    'project_funder',
    'taxonomy_name',
    'transgenic_line_name',
    'age',
    'age_unit',
    'sex',
    'organ',
    'organ_substructure',
    'assay',
    'slicing_direction']

