attrs = [
    'project_name',
    'collection',
    'project_description',
    'background_strain',
    'image_filename_pattern',
    'taxonomy_name',
    'transgenic_line_name',
    'age',
    'age_unit',
    'sex',
    'organ',
    'organ_substructure',
    'assay',
    'slicing_direction']
